title: Settings
data:
  logo: blog-logo.png
  site_name: '🎉TuanTQ | Chia sẻ kiến thức lập trình'
  meta_description: 'TuanTQ | Chia sẻ kiến thức lập trình | Tips and Trick | Snippet Code | PHP'
  og_image: programming-code-made-with-binary-code-coding-hacker-background-digital-binary-data-streaming-digita.jpg
